[tool.poetry]
name = "A2A"
version = "0.1.0"
description = "Project to look at A2A communication"
authors = ["Benjamin"]

[tool.poetry.dependencies]
python = "^3.13"
pydantic = "^2.11.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry-core.masonry.api"